version: 2

jobs:
  test:
    working_directory: ~/wachunga/car-share-fare
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install and build package
          command: yarn install --frozen-lockfile
      - run:
          name: Run tests
          command: yarn test --runInBand --no-cache
